ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.rashidyusubov.musicserver.SerializationKt.configureSerialization
      - com.rashidyusubov.musicserver.RoutingKt.configureRouting
